### ISSUE TITLE
Consider introducing releases and API versioning

### ISSUE THREAD

**Issue by Teebor-Choka** [mrlesmithjr/ansible-kvm#31]
Hi and thanks for this amazing role.

I created a pull request #29 (molecule testing using Travis CI, code refactoring, external dependency removals...). All the changes were internal and they have not touched the external API yet.

However, in case of future (API breaking) changes, it would be prudent to introduce versioning to API (e.g. using releases).

Please, consider creating releases indicating possible API changes for future users and allowing them to fix to a specific `major.minor.revision` release instead of a commit ID.

**Comment by mrlesmithjr** [comment]
@Teebor-Choka Thanks for the PR. I just went through it all and it all looks good. I left a review to change one thing only. I also agree, we should implement versions for this role.
